FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

# Resolve npm certification error
RUN npm config set strict-ssl=false
RUN npm config set registry http://registry.npmjs.org
RUN set NODE_TLS_REJECT_UNAUTHORIZED=0

RUN npm install

COPY . .

CMD ["npm", "run", "start"]