version: '3'
services: 
  web:
    build:
      context: . # which directory to look in for dockerfiles
      dockerfile: Dockerfile.dev # name of the dockerfile to build
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node/modules
      - ./app
    command: ["npm", "run", "test"] # Override default command of the dockerfile
    # run test instead of build dev server